config/routes.rb
Rails.application.routes.draw do

  # Authentication
  devise_for :users

  # Does not fix the problem when login out
  # devise_for :users do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  # Fixes the problem when login out
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # Changing the default main page to the posts' index view
  # get '/', to: 'pages#index'
  root 'pages#index'
  #
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'gallery', to: 'pages#gallery'
  get 'index', to: 'pages#index'
  get 'services', to: 'pages#services'

  resources :message



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/message_controller.rb
class MessageController < ApplicationController


  def new

  end

  def create

    # Receives the parameters using the function
    @message = Message.new message_params

    # Gets the full_name field
    @full_name = @message.full_name

    # If the message is properly saved in the DB...
    if @message.save
      # It redirects to the contact page with a notice
      # redirect_to contact_path, :notice => 'Su mensaje ha sido enviado', :notice_header => 'Gracias ' + @full_name
      redirect_to contact_path, :notice => 'Gracias ' + @full_name + '. ' + 'Su mensaje ha sido enviado'
    else
      # redirect_to contact_path, :notice => 'Sus mensaje no se pudo enviar', :notice_header => 'Error en el sistema'
      redirect_to contact_path, :notice => 'Lo sentimos ' + @full_name + '. ' + 'Su mensaje no se pudo enviar' ''
    end

  end


  private

  # Definition of the strong params
  def message_params
    params.require(:message).permit(:full_name, :email, :phone, :body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # helper PagesHelper::show_banners

  # layout "index_layout", :only => [:about, :contact, :gallery, :index, :services]

  # Shows the about view
  def about

  end

  # Shows the contact view
  def contact

  end

  # Shows the gallery view
  def gallery

  end

  # Shows the index view
  def index

  end

  # Shows the services view
  def services

  end


end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/pages_helper.rb
module PagesHelper


  # Determines if the current route is the index or the root
  def show_banners

    # current_page?(:controller => 'pages', :action => 'index') or current_page?(root_url)
    #
    # It works!
    # current_page?(index_path) ? true : (current_page?(root_path) ? true : false)

    # It works!
    #   if current_page?(index_path) or current_page?(root_path)
    #      true
    #   else
    #      false
    #   end

    # It works!
    (current_page?(index_path) || current_page?(root_path)) ? true : false

  end

end

app/views/layouts/_alerts.html.erb
<!--<p class="notice"><%#= notice %></p>-->
<!--<p class="alert"><%#= alert %></p>-->


<!--<div id="div_notice_header" class="notice" hidden><%#= notice_header %></div>-->
<div id="div_notice" class="notice" hidden><%= notice %></div>
<div id="div_alert" class="alert" hidden><%= alert %></div>

app/views/layouts/application_original.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RorBeautySalonMayde</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/pages/contact.html.erb
<!-- contact -->
<div class="contact">
  <div class="container">
    <div class="wthree_head_section">
      <h3 class="w3l_header">Contacte con <span>Nosotros</span></h3>
      <p>
        Disfrute de un tratamiento facial o aromaterapia para una ocasión especial. Nuestros servicios
        de belleza y cuidado de la piel se adaptarán a cada necesidad de belleza.
      </p>
    </div>
    <div class="gal-btm">
      <div class="map-home">
        <div class="col-md-4 drop-pad sign-gd-two">
          <h3>Contáctenos</h3>
          <ul>
            <!--<li><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i> 1234k Avenue, 4th block,-->
            <li><i class="fa fa-map-marker" aria-hidden="true"></i> Altahabana, Boyeros,
              <span>Habana</span></li>
            <!--<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i> +1234 567 567</li>-->
            <li><i class="fa fa-phone" aria-hidden="true"></i>(+535) 357-5012</li>
            <li>
              <!--<i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a>-->
              <i class="fa fa-envelope" aria-hidden="true"></i><a href="maydemillenium@gmail.com">maydemillenium@gmail.com</a>
            </li>
          </ul>
          <h3 class="connect">Conéctese</h3>
          <ul class="top-links">
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
        <div class="col-md-8 contact-w3ls">

          <!--          <form action="#" method="post">-->
          <!--            <div class="col-md-5 col-sm-5 contact-left agileits-w3layouts">-->

          <!--              <div class="f-control">-->
          <!--                <label class="header">Nombre Completo <span>:</span></label>-->
          <!--                <input type="text" name="First Name" placeholder="Nombre Completo" required="">-->
          <!--              </div>-->

          <!--              <div class="f-control">-->
          <!--                <label class="header">Email <span>:</span></label>-->
          <!--                <input type="email" class="email" name="Email" placeholder="Email" required="">-->
          <!--              </div>-->

          <!--              <div class="f-control">-->
          <!--                <label class="header">Número telefónico <span>:</span></label>-->
          <!--                <input type="text" name="Number" placeholder="Número telefónico" required="">-->
          <!--              </div>-->
          <!--            </div>-->
          <!--            <div class="col-md-7 col-sm-7 contact-right agileits-w3layouts">-->

          <!--              <label class="header">Mensaje <span>:</span></label>-->
          <!--              <textarea name="Message" placeholder="Mensaje" required=""></textarea>-->


          <!--            </div>-->
          <!--            <div class="clearfix"></div>-->
          <!--            <input type="submit" value="Enviar">-->
          <!--          </form>-->










          <%#= form_for :message, url: message_path do |f| %>
          <!--Salva pero no confirma-->
          <%= form_for :message, :url => {:action => "create", :controller => "message"}, id: 'new_message_form' do |f| %>
            <!-- Salva pero no confirma-->
            <%#= form_for :message, :url => {:action => "create", :controller => "message"}, id: 'new_message_form', :onsubmit => "confirm('Desea hacerlo?');return false" do |f| %>



            <div class="col-md-5 col-sm-5 contact-left agileits-w3layouts">
              <div class="f-control">
                <%= f.label :full_name, class: 'header' do %>
                  Nombre Completo <span>:</span>
                <%- end %>

                <%= f.text_field :full_name, placeholder: 'Nombre Completo', :required => true %>
              </div>

              <div class="f-control">
                <%= f.label :email, class: 'header' do %>
                  Email <span>:</span>
                <%- end %>

                <%= f.email_field :email, placeholder: 'Email', :required => true, class: 'email' %>
              </div>

              <div class="f-control">
                <%= f.label :phone, class: 'header' do %>
                  Número telefónico <span>:</span>
                <%- end %>

                <%= f.text_field :phone, placeholder: 'Número telefónico', :required => true %>
              </div>
            </div>

            <div class="col-md-7 col-sm-7 contact-right agileits-w3layouts">
              <%= f.label :body, class: 'header' do %>
                Mensaje <span>:</span>
              <%- end %>

              <%= f.text_area :body, placeholder: 'Mensaje', :required => true %>
            </div>

            <div class="clearfix"></div>

            <%= f.submit 'Enviar' %>
            <%#= f.submit 'Enviar', id: 'btn_send_message', data: {confirm: 'Are you sure?'} %>
            <%#= f.submit 'Enviar', data-confirm => "Are you sure?" %>
            <%#= f.submit 'Enviar', data: {confirm: "Seguro que desea enviar el mensaje?"} %>
            <%#= f.submit 'Enviar', :onrelease => "return confirm('Seguro que desea enviar el mensaje?')" %>

            <!-- Now it is on top of yield, in the application layout -->
            <!--<div id="div_notice" hidden><%#= notice %></div>-->

          <% end %>


        </div>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>
<!-- //contact -->
<!-- map -->
<div class="frame">
  <!--  <iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d96704.53970617482!2d-74.05317380152253!3d40.76165377918555!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sNew+York+City+beauty+salon!5e0!3m2!1sen!2sin!4v1512820386082" allowfullscreen></iframe>-->
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6173.5951788002785!2d-82.39817076472117!3d23.066266066356466!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88cd70855b610a0b%3A0x6796b7c2d849e1e!2sAgromercado+Altahabana!5e0!3m2!1ses-419!2sus!4v1544874848256" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
<!-- //map -->

app/views/pages/gallery.html.erb
<!--gallery-->
<div class="gallery">
  <div class="container">
    <div class="wthree_head_section">
      <h3 class="w3l_header">Nuestra <span>Galería</span></h3>
      <p>
        Disfrute de un tratamiento facial o aromaterapia para una ocasión especial. Nuestros servicios
        de belleza y cuidado de la piel se adaptarán a cada necesidad de belleza.
      </p>
    </div>
    <div class="gallery-info">
      <div class="col-md-3 gallery-grids">
        <a href="<%= image_url 'p1.jpg' %>" class="gallery-box" data-lightbox="example-set" data-title="Realizamos desrizado del cabello">
          <%= image_tag 'p1.jpg', alt: "", class: 'img-responsive zoom-img' %>
        </a>

      </div>
      <div class="col-md-3 gallery-grids">
        <a href="<%= image_url 'p2.jpg' %>" class="gallery-box" data-lightbox="example-set" data-title="Corte de cabello">
          <%= image_tag 'p2.jpg', alt: "", class: 'img-responsive zoom-img' %>
        </a>
      </div>
      <div class="col-md-3 gallery-grids">
        <a href="<%= image_url 'p3.jpg' %>" class="gallery-box" data-lightbox="example-set" data-title="Tratamiento podológico">
          <%= image_tag 'p3.jpg', alt: "", class: 'img-responsive zoom-img' %>
        </a>
      </div>
      <div class="col-md-3 gallery-grids">
        <a href="<%= image_url 'p4.jpg' %>" class="gallery-box" data-lightbox="example-set" data-title="Peinados de alta complejidad">
          <%= image_tag 'p4.jpg', alt: "", class: 'img-responsive zoom-img' %>
        </a>
      </div>
      <div class="col-md-3 gallery-grids">
        <a href="<%= image_url 'p5.jpg' %>" class="gallery-box" data-lightbox="example-set" data-title="Tratamiento delicado de pestañas">
          <%= image_tag 'p5.jpg', alt: "", class: 'img-responsive zoom-img' %>
        </a>
      </div>
      <div class="col-md-3 gallery-grids">
        <a href="<%= image_url 'p6.jpg' %>" class="gallery-box" data-lightbox="example-set" data-title="Pintado profesional de uñas">
          <%= image_tag 'p6.jpg', alt: "", class: 'img-responsive zoom-img' %>
        </a>
      </div>
      <div class="col-md-3 gallery-grids">
        <a href="<%= image_url 'p7.jpg' %>" class="gallery-box" data-lightbox="example-set" data-title="Cuidado de las cutículas">
          <%= image_tag 'p7.jpg', alt: "", class: 'img-responsive zoom-img' %>
        </a>
      </div>
      <div class="col-md-3 gallery-grids">
        <a href="<%= image_url 'p8.jpg' %>" class="gallery-box" data-lightbox="example-set" data-title="">
          <%= image_tag 'p8.jpg', alt: "", class: 'img-responsive zoom-img' %>
        </a>
      </div>
      <div class="col-md-3 gallery-grids">
        <a href="<%= image_url 'p9.jpg' %>" class="gallery-box" data-lightbox="example-set" data-title="">
          <%= image_tag 'p9.jpg', alt: "", class: 'img-responsive zoom-img' %>
        </a>
      </div>
      <div class="col-md-3 gallery-grids">
        <a href="<%= image_url 'p10.jpg' %>" class="gallery-box" data-lightbox="example-set" data-title="">
          <%= image_tag 'p10.jpg', alt: "", class: 'img-responsive zoom-img' %>
        </a>
      </div>
      <div class="col-md-3 gallery-grids">
        <a href="<%= image_url 'p11.jpg' %>" class="gallery-box" data-lightbox="example-set" data-title="">
          <%= image_tag 'p11.jpg', alt: "", class: 'img-responsive zoom-img' %>
        </a>
      </div>
      <div class="col-md-3 gallery-grids">

        <a href="<%= image_url 'p12.jpg' %>" class="gallery-box" data-lightbox="example-set" data-title="">
          <%= image_tag 'p12.jpg', alt: "", class: 'img-responsive zoom-img' %>
        </a>

      </div>

      <div class="clearfix"></div>
    </div>



    <!--    <script src="lightbox-plus-jquery.min.js"></script>-->
    <%= javascript_include_tag 'lightbox-plus-jquery.min.js' %>

    <!--    <script src="lightbox-plus-jquery.js"></script>-->
  </div>
</div>
<!--//gallery-->












app/views/pages/index.html.erb
<!-- Modal1 -->
<div class="modal fade" id="myModal4" tabindex="-1" role="dialog">
  <div class="modal-dialog">


    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4>Beauty Salon</h4>

        <%= image_tag '11.jpg', alt: '', class: 'img-responsive' %>

        <h5>Neque porro quisquam est qui dolorem </h5>
        <p>Ut in ligula sollicitudin, auctor elit vel, mollis tortor. Nullam id magna in eros mollis porttitor vel et
          eros.Phasellus
          sed iaculis nibh, non suscipit tortor. Aenean ante massa, lobortis et dolor eget, sollicitudin luctus arcu.
          Donec eros
          tortor, ultrices in lectus quis, aliquet commodo lectus.Donec eros tortor, ultrices in lectus quis, aliquet
          commodo
          lectus.</p>
      </div>
    </div>
  </div>
</div>
<!-- //Modal1 -->
<!-- Latest News -->
<div class="practice-areas">
  <div class="container">
    <div class="wthree_head_section">
      <h3 class="w3l_header">Nuestros <span>Servicios</span></h3>
      <p>
        Disfrute de un tratamiento facial o aromaterapia para una ocasión especial. Nuestros servicios
        de belleza y cuidado de la piel se adaptarán a cada necesidad de belleza.
      </p>
    </div>
    <div class="area-main">
      <div class="col-md-6 area-inner">
        <div class="area-img1">
        </div>
        <div class="area-right p1">
          <h5>FACIAL</h5>
          <p class="para-w3-agile">Phasellus sed iaculis nibh, non suscipit tortor. Aenean ante massa, lobortis et dolor
            eget, sollicitudin luctus arcu.
            Donec eros tortor, ultrices in lectus quis, aliquet commodo lectus.</p>
        </div>
      </div>
      <div class="col-md-6 area-inner">
        <div class="area-img2">
        </div>
        <div class="area-right p2">
          <h5>MAQUILLAJE</h5>
          <p class="para-w3-agile">Phasellus sed iaculis nibh, non suscipit tortor. Aenean ante massa, lobortis et dolor
            eget, sollicitudin luctus arcu.
            Donec eros tortor, ultrices in lectus quis, aliquet commodo lectus.</p>
        </div>
      </div>
    </div>
    <div class="area-main">
      <div class="col-md-6 area-inner">
        <div class="area-right p3">
          <h5>UÑAS</h5>
          <p class="para-w3-agile">Phasellus sed iaculis nibh, non suscipit tortor. Aenean ante massa, lobortis et dolor
            eget, sollicitudin luctus arcu.
            Donec eros tortor, ultrices in lectus quis, aliquet commodo lectus.</p>
        </div>
        <div class="area-img3">
        </div>
      </div>
      <div class="col-md-6 area-inner">
        <div class="area-right p4">
          <h5>CABELLO</h5>
          <p class="para-w3-agile">Phasellus sed iaculis nibh, non suscipit tortor. Aenean ante massa, lobortis et dolor
            eget, sollicitudin luctus arcu.
            Donec eros tortor, ultrices in lectus quis, aliquet commodo lectus.</p>
        </div>
        <div class="area-img4">
        </div>
      </div>
    </div>
  </div>
</div>
<!-- //Latest News -->
<!-- wthree-mid -->
<div class="wthree-mid jarallax">
  <div class="container">
    <h3>Nisl amet dolor sit ipsum veroeros sed blandit</h3>
    <p>Standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
      a type specimen book</p>
    <div class="botton">
      <a href="<%= about_path %>">Acerca de</a>
    </div>
  </div>
</div>
<!-- //wthree-mid -->
<!-- pricing -->
<div class="w3ls-section wthree-pricing" id="pricing">
  <div class="container">
    <div class="wthree_head_section">
      <h3 class="w3l_header">Packages <span>Pricing</span></h3>
      <p>
        Disfrute de un tratamiento facial o aromaterapia para una ocasión especial. Nuestros servicios
        de belleza y cuidado de la piel se adaptarán a cada necesidad de belleza.
      </p>
    </div>
    <div class="pricing-grids-info">
      <div class="pricing-grid grid-one">
        <div class="w3ls-top">
          <h3>Básico</h3>
        </div>
        <div class="w3ls-bottom">
          <ul class="count">
            <li>Extensiones de Pelo</li>
            <li>Aplicación de Maquillaje</li>
            <li>Facial</li>
            <li>Uñas</li>
            <li>Estilo</li>
          </ul>
          <h4> 200<span class="sup">$</span></h4>
          <div class="more">
            <a href="#">Contáctenos'</a>
          </div>
        </div>
      </div>
      <div class="pricing-grid grid-two">
        <div class="w3ls-top">
          <h3>Clásico</h3>
        </div>
        <div class="w3ls-bottom">
          <ul class="count">
            <li>Hair Extension</li>
            <li>Makeup Application</li>
            <li>Facial</li>
            <li>Nails</li>
            <li>Styling</li>
          </ul>
          <h4> 350<span class="sup">$</span></h4>
          <div class="more">
            <a href="#">Contáctenos</a>
          </div>
        </div>
      </div>
      <div class="pricing-grid grid-three">
        <div class="w3ls-top">
          <h3>Oro</h3>
        </div>
        <div class="w3ls-bottom">
          <ul class="count">
            <li>Hair Extension</li>
            <li>Makeup Application</li>
            <li>Facial</li>
            <li>Nails</li>
            <li>Styling</li>
          </ul>
          <h4> 500<span class="sup">$</span></h4>
          <div class="more">
            <a href="#">Contáctenos</a>
          </div>
        </div>
      </div>
      <div class="zb pricing-grid grid-four">
        <div class="w3ls-top">
          <h3>Platino</h3>
        </div>
        <div class="w3ls-bottom">
          <ul class="count">
            <li>Hair Extension</li>
            <li>Makeup Application</li>
            <li>Facial</li>
            <li>Nails</li>
            <li>Styling</li>
          </ul>
          <h4> 800<span class="sup">$</span></h4>
          <div class="more">
            <a href="#">Contáctenos</a>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
      <!--End-slider-script-->
    </div>
  </div>
</div>
<!--//pricing-->
<!-- counter -->
<div class="services-bottom stats services jarallax">
  <div class="banner-dott1">
    <div class="container">
      <div class="wthree_head_section">
        <h3 class="w3l_header two">Nuestras <span>Estadísticas</span></h3>
        <p class="tho">Treat yourself to a facial or celebrating a special occasion, aromatherapy, our beauty
          and skin care services will suit every beauty need.</p>
      </div>
      <div class="wthree-agile-counter">
        <div class="col-md-3 w3_agile_stats_grid-top">
          <div class="w3_agile_stats_grid">
            <div class="agile_count_grid_left">
              <!--<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>-->
              <span class="fa fa-cog" aria-hidden="true"></span>
            </div>
            <div class="agile_count_grid_right">
              <p class="counter">324</p>
            </div>
            <div class="clearfix"></div>
            <h4>Servicios</h4>
          </div>
        </div>
        <div class="col-md-3 w3_agile_stats_grid-top">
          <div class="w3_agile_stats_grid">
            <div class="agile_count_grid_left">
              <!--<span class="glyphicon glyphicon-user" aria-hidden="true"></span>-->
              <span class="fa fa-user" aria-hidden="true"></span>
            </div>
            <div class="agile_count_grid_right">
              <p class="counter">543</p>
            </div>
            <div class="clearfix"></div>
            <h4>Clientes Felices</h4>
          </div>
        </div>
        <div class="col-md-3 w3_agile_stats_grid-top">
          <div class="w3_agile_stats_grid">
            <div class="agile_count_grid_left">
              <!--<span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>-->
              <span class="fa fa-thumbs-up" aria-hidden="true"></span>
            </div>
            <div class="agile_count_grid_right">
              <p class="counter">434</p>
            </div>
            <div class="clearfix"></div>
            <h4>Encantados</h4>
          </div>
        </div>
        <div class="col-md-3 w3_agile_stats_grid-top">
          <div class="w3_agile_stats_grid">
            <div class="agile_count_grid_left">
              <span class="fa fa-trophy" aria-hidden="true"></span>
            </div>
            <div class="agile_count_grid_right">
              <p class="counter">234</p>
            </div>
            <div class="clearfix"></div>
            <h4>Premios</h4>
          </div>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>
<!-- //counter -->
<!-- Clients -->
<div class="clients-main" id="clients">
  <div class="container">
    <!-- Owl-Carousel -->
    <div class="wthree_head_section">
      <h3 class="w3l_header">Opiniones <span>de Clientes</span></h3>
      <p>
        Disfrute de un tratamiento facial o aromaterapia para una ocasión especial. Nuestros servicios
        de belleza y cuidado de la piel se adaptarán a cada necesidad de belleza.
      </p>
    </div>
    <div id="owl-demo" class="owl-carousel text-center clients-right">
      <div class="item g1">
        <div class="agile-dish-caption">
          <h4>John Smith</h4>
          <span>Lorem Ipsum</span>
        </div>
        <%= image_tag 'c1.jpg', alt: '', class: 'lazyOwl' %>
        <div class="clearfix"></div>
        <p class="para-w3-agile"><span class="fa fa-quote-left" aria-hidden="true"></span>Duis nulla nulla, faucibus id
          diam ac, luctus sodales purus.
          Quisque nibh ipsum,Ut accumsan.</p>
      </div>
      <div class="item g1">
        <div class="agile-dish-caption">
          <h4>Jecy Deoco</h4>
          <span>Lorem Ipsum</span>
        </div>
        <%= image_tag 'c2.jpg', alt: '', class: 'lazyOwl' %>

        <div class="clearfix"></div>
        <p class="para-w3-agile"><span class="fa fa-quote-left" aria-hidden="true"></span>Duis nulla nulla, faucibus id
          diam ac, luctus sodales purus.
          Quisque nibh ipsum,Ut accumsan.</p>
      </div>
      <div class="item g1">
        <div class="agile-dish-caption">
          <h4>Devid Fahim</h4>
          <span>Lorem Ipsum</span>
        </div>
        <%= image_tag 'c3.jpg', alt: '', class: 'lazyOwl' %>
        <div class="clearfix"></div>
        <p class="para-w3-agile"><span class="fa fa-quote-left" aria-hidden="true"></span>Duis nulla nulla, faucibus id
          diam ac, luctus sodales purus.
          Quisque nibh ipsum,Ut accumsan.</p>
      </div>
      <div class="item g1">
        <div class="agile-dish-caption">
          <h4>Honey Jisa</h4>
          <span>Lorem Ipsum</span>
        </div>
        <%= image_tag 'c1.jpg', alt: '', class: 'lazyOwl' %>
        <div class="clearfix"></div>
        <p class="para-w3-agile"><span class="fa fa-quote-left" aria-hidden="true"></span>Duis nulla nulla, faucibus id
          diam ac, luctus sodales purus.
          Quisque nibh ipsum,Ut accumsan.</p>
      </div>
      <div class="item g1">
        <div class="agile-dish-caption">
          <h4>Jecy Deoco</h4>
          <span>Lorem Ipsum</span>
        </div>
        <%= image_tag 'c2.jpg', alt: '', class: 'lazyOwl' %>
        <div class="clearfix"></div>
        <p class="para-w3-agile"><span class="fa fa-quote-left" aria-hidden="true"></span>Duis nulla nulla, faucibus id
          diam ac, luctus sodales purus.
          Quisque nibh ipsum,Ut accumsan.</p>
      </div>
      <div class="item g1">
        <div class="agile-dish-caption">
          <h4>Devid Fahim</h4>
          <span>Lorem Ipsum</span>
        </div>
        <%= image_tag 'c3.jpg' %>
        <div class="clearfix"></div>
        <p class="para-w3-agile"><span class="fa fa-quote-left" aria-hidden="true"></span>Duis nulla nulla, faucibus id
          diam ac, luctus sodales purus.
          Quisque nibh ipsum,Ut accumsan.</p>
      </div>
    </div>
    <!--// Owl-Carousel -->
  </div>
</div>
<!--// Clients -->